#!/bin/bash

set -eu

# include common script
. "$(dirname "$0")"/common.sh

title "Building new documentation output...\n"

repo_root="$(pwd)"

mkdir -p out

pushd "$BUILDER_ROOT"
node index.js "$repo_root"
cp -a natives_test.json "$repo_root/out/natives.json"
node build-template.js lua > "$repo_root/out/natives.lua"
node build-template.js reference > "$repo_root/out/natives.html"
popd