#!/bin/bash

# configuration
GENERATOR_PATH="$1/compatgen.js"
OUTPUT_FILE=${2:-"./out/natives_global_client_compat.lua"}
INPUT_FILE=${3:-"./in/natives_global_client_compat.lua"}
IGNORE_MISSING_INPUT=${4:-false}
FORCE_UPDATE=${5:-false}
DAYS_SINCE_DATE=${6:-2023-01-01} #YYYY-MM-DD
MAJOR=${7:-2}
MINOR=${8:-0}

# execution
node $GENERATOR_PATH --set-version=$MAJOR.$MINOR --force=$FORCE_UPDATE --start-date=$DAYS_SINCE_DATE --out=$OUTPUT_FILE --in=$INPUT_FILE --ignore-missing-in=$IGNORE_MISSING_INPUT
